### PR TITLE
added natural terrain elements

### PR DESCRIPTION
**Pull request by ColeOSRF**
This adds back in the terrain elements but I've placed more objects for more density. I've also added mesh colliders for the models. Some are still missing and there are some adjustments that need to be made. I've also updated the heightmap since I made some small changes to that. As long as there are no critical issues then we can probably go ahead and merge.

### CODE REVIEW

**Comment by iche033** [comment]
When I right click on the Terrain Objects and view Collision, and zoom all the way out, I see:

Screenshot from 2023-08-17 17-13-36

The collisions cover the enter area. Maybe the pose / scale is not correct?

**Comment by ColeOSRF** [comment]
Good catch. I had some colliders pointing to the wrong mesh. Should be fixed now.

**Comment by ColeOSRF** [comment]
I also get an error when running the world about the geometry for collisions not being able to be generated. However the collision geometry is there in the scene so I'm not sure why those errors are showing.

**Comment by iche033** [comment]
The updated collisions look good to me!

> I also get an error when running the world about the geometry for collisions not being able to be generated. However the collision geometry is there in the scene so I'm not sure why those errors are showing.

I'm also seeing the same error msgs but the collisions are there. I'll look into it

**Review by iche033 — APPROVED** [review]

**Pull request merged**
