### PR TITLE
Updated house model and added furniture

### PR DESCRIPTION
**Pull request by ColeOSRF**
I updated the house model so it's fully textured, stairs added, mesh fixed, etc. and opened up a couple of the doors so robots can go between the outside and inside. I also added most of the furniture although there are a few missing items. These furniture models will eventually be added as individual models on Fuel. 

Note that I've removed all the terrain models such as rocks and trees. I'll be adding these back in with more density in a later PR.

### CODE REVIEW

**Review by caguero — COMMENTED** [review]
All look good to me besides one minor comment: there's something rectangular floating in the air of one door.

Screenshot from 2023-08-11 18-48-36

**Comment by iche033** [comment]
Looks good!

Just found a hidden room beneath the stairs. Needs a secret passage to get there :)
 
secret_room

**Comment by iche033** [comment]
@ColeOSRF should we get these assets in first and the new changes can come later?

**Comment by ColeOSRF** [comment]
Yeah let's do that. I've already addressed these issues so they'll be reflected in the next PR.

**Pull request merged**
