### PR TITLE
Demo world for mimic mechanisms

### PR DESCRIPTION
**Pull request by scpeters**
Requires bullet-featherstone

Screenshot 2023-09-25 at 10 21 35 PM
Screenshot 2023-09-25 at 10 21 55 PM

### CODE REVIEW

**Comment by scpeters** [comment]
https://github.com/gazebosim/harmonic_demo/assets/3650755/75c44eda-0c58-44a4-a5a8-70d44da2ebe0

**Comment by scpeters** [comment]
I added some color to indicate which joint axes have mimic constraints

Screenshot 2023-09-25 at 11 11 59 PM
Screenshot 2023-09-25 at 11 12 43 PM

https://github.com/gazebosim/harmonic_demo/assets/3650755/d81580da-ff42-4c92-a02c-a9c08cc40a1d

**Review by iche033 — APPROVED** [review]
nice, works for me. I think we could also add this world to `gz-sim/examples/world`

**Comment by scpeters** [comment]
the rack axis direction was backwards; it's being fixed in #23 

here are updated images:

Screenshot 2023-09-25 at 11 11 59 PM
Screenshot 2023-09-25 at 11 12 43 PM

https://github.com/gazebosim/harmonic_demo/assets/3650755/a3992788-18e8-4976-bfe3-10aa8f1ef188

**Pull request merged**
