### PR TITLE
Fix projector pose and update mascot position

### PR DESCRIPTION
**Pull request by iche033**
# 🦟 Bug fix

## Summary

Updated the pose of the projector to better the match the mesh files. The red cube shows the updated projector location:

mascot_projector

Because the projector is now tilted upwards, it was projecting part of the texture onto the ceiling at the original location (on top of the desk). So I moved the harmonic mascot down to the floor in front of the bed

mascot_location

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Review by azeey — APPROVED** [review]
LGTM!

I noticed a few things:
* The projection seems to go through walls
image
* Having the projector slows down orbit view on my system
* The Harmonic mascot looks washed out. e.g. you can't see the edge of the box in the following. Maybe turning down ambient light might help
image

**Comment by ColeOSRF** [comment]
I added some lights to the house which will help with the washed out look.

**Comment by iche033** [comment]
> The projection seems to go through walls

unfortunately that's another limitation of ogre2's implementation. It does not do occlusion checking so the projector shines through. I moved the mascot to the side of the bed so it does not project through to the vanity.

> Having the projector slows down orbit view on my system

hmm is it on gpu machine?

> The Harmonic mascot looks washed out. e.g. you can't see the edge of the box in the following. Maybe turning down ambient light might help

that's due to lack of lights so the rendering is quite flat. Lights added in https://github.com/gazebosim/harmonic_demo/pull/18  will help.

**Comment by iche033** [comment]
While testing the projector, I found an issue that point lights are casting shadows on the rotation tool visual, ticketed https://github.com/gazebosim/gz-rendering/issues/916. So I disabled `<cast_shadows>` for the point lights added in https://github.com/gazebosim/harmonic_demo/pull/18. I also toned down the specular property and soften the point lights so that the walls and other objects do not end up looking too shiny. FYI @ColeOSRF.

**Pull request merged**
