### PR TITLE
Double Pendulum Sculpture for Auto Inertia Demo

### PR DESCRIPTION
**Pull request by jasmeet0915**
# 🎉 New feature

Added a demo for the Auto Inertia Feature in the form of a double pendulum-based desktop sculpture inspired by Swinging Sticks. This was originally intended for the office desk on the upper floor however the size was a bit too large for that so I kept it on the dining table as a centerpiece instead :p

Here's a gif of the pendulum in action:

pendulum_sculpture

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Review by quarkytale — APPROVED** [review]
Looks good to me, but I'll wait for @iche033 or @ColeOSRF to take a glance!

**Comment by iche033** [comment]
nice, that's pretty cool demo!

I noticed that the collision of the base overhangs a little. Maybe shift it inward a little? Otherwise looks good to me!
sculpture_demo

**Comment by jasmeet0915** [comment]
@iche033 Thanks for pointing that out! I had changed the visual of the base but forgot to do that for the collision. I have corrected the collision in [db831a3](https://github.com/gazebosim/harmonic_demo/pull/13/commits/db831a3b2274abc830e3ad0bba7b6cecc7b51141).

**Review by iche033 — APPROVED** [review]
looks good to me!

**Pull request merged**
